export { default as Hero } from "./Hero"
export { default as SubHero } from "./SubHero"
export { default as WhyUs } from "./WhyUs"
export { default as AchieveGoals } from "./AchieveGoals"
export { default as FAQs } from "./FAQs"
export { default as GlobalImpact } from "./GlobalImpact"